### ISSUE TITLE
Enable debug mode

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/coredns-crd-plugin#38]
Make it possible to explicitly activate debug mode, which would also display messages `log.Debugf(...)`.

 - See if it's already in CoreDNS somewhere
 - k8s_crd plugin may be producing too many INFO messages, try overwriting them with DEBUG
 - find places where it would be useful to add DEBUG and extend the plugin to include those places
 - take inspiration from k8gb, e.g: see [this](https://github.com/k8gb-io/k8gb/issues/331)

**Comment by ytsarev** [comment]
@kuritka is this one still valid?

**Comment by kuritka** [comment]
Hi @ytsarev , 
regarding k8gb_crd plugin, we set extra logging by add `log` plugin into `extra_plugins` see: [[1]](https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/values.yaml#L34), [[2]](https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/templates/coredns-cm.yaml#L13-L16)

By definition: coreDNS plugin _*log - enables query logging to standard output._

Log filtering goes according to the settings of this coreDNS plugin, see [examples](https://github.com/coredns/coredns/tree/master/plugin/log#examples).

So from my pov we can close.

**Comment by ytsarev** [comment]
Cool, thanks for clarification, let's close this one then.
